"""OpportunityReport model: a persisted AI-generated new-product opportunity report."""

from datetime import datetime

from sqlalchemy import Column, Integer, Text, JSON, DateTime, ForeignKey

from app.database.base import Base


class OpportunityReport(Base):
    """
    The final deliverable of the pipeline: a concrete new-product
    opportunity recommendation for a category (optionally inspired by an
    existing product), generated by
    app.ai.agent.FurnitureInsightAgent.recommend_product and enriched
    with RAG lookups over previously generated reports (app.ai.rag).
    """

    __tablename__ = "opportunity_reports"

    id = Column(Integer, primary_key=True, index=True)
    category_id = Column(Integer, ForeignKey("categories.id"), nullable=False, index=True)
    # Text, not String(N) - LLM-generated product names are unbounded in
    # practice, and a capped length only fails on Postgres (SQLite ignores
    # VARCHAR limits), i.e. exactly in production. Same rationale as
    # Product.name - see app/models/product.py.
    product_name = Column(Text, nullable=False)
    target_customer = Column(Text, nullable=False)
    pain_points = Column(JSON, nullable=False, default=list)
    solution = Column(Text, nullable=False)
    features = Column(JSON, nullable=False, default=list)
    selling_points = Column(JSON, nullable=False, default=list)
    created_at = Column(DateTime, default=datetime.utcnow, nullable=False)

    def __repr__(self) -> str:  # pragma: no cover
        return f"<OpportunityReport id={self.id} category_id={self.category_id} product_name={self.product_name!r}>"
